# Generated by Django 5.1.4 on 2025-02-17 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_work', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('working_days', models.CharField(max_length=100)),
                ('work_format', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('rules', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_vacancy_app.vacancy')),
            ],
        ),
    ]
